# 1.数据类型

## 类型推断

In [1]:
import torch
# type check
a = torch.randn(2,3)
print(a.type())
print(type(a))
print(isinstance(a,torch.FloatTensor))

torch.FloatTensor
<class 'torch.Tensor'>
True


In [3]:
data = a
data = data.cuda()
print(isinstance(data,torch.cuda.FloatTensor))

True


## 标量（标量dimsension 0/rank 0(常用于loss)）

In [4]:
# 标量dimsension 0/rank 0(常用于loss)
b = torch.tensor(1.3)
print(b)
print(b.shape)   #shape是成员
print(len(b.shape))
print(b.size())#size()是成员函数

tensor(1.3000)
torch.Size([])
0
torch.Size([])


## 张量（张量dimension为1，常用于bias）

In [10]:
print(torch.tensor([1.1]))
a = torch.tensor([1.1,2.1])
print(a.type())

tensor([1.1000])
torch.FloatTensor


In [17]:
torch.FloatTensor(1)#这个1就是dimension了

tensor([-8.0832e+25])

In [18]:
torch.FloatTensor(2)

tensor([-8.0831e+25,  4.5797e-41])

In [23]:
import numpy as np
data   = np.ones(2)
torch_data = torch.from_numpy(data)

In [28]:
torch_data

tensor([1., 1.], dtype=torch.float64)

In [27]:
print(torch_data.shape)
print(torch_data.type())

torch.Size([2])
torch.DoubleTensor


## 张量dimension2(常用于batch,linear input的输入)

In [29]:
d = torch.randn(2,3)#正态分布，同时用FloatTensor也可以
print(d)

tensor([[ 1.0152, -0.0950,  0.4634],
        [ 0.2911, -1.7506,  0.6098]])


In [30]:
print(d.shape)

torch.Size([2, 3])


In [31]:
d = torch.FloatTensor(2,3)

In [32]:
d

tensor([[-8.0829e+25,  4.5797e-41,  6.8410e+00],
        [ 3.0740e-41,  0.0000e+00,  0.0000e+00]])

## dimension是维度，这里就是2
## shape/size:就是形状，这里是[2,3]
## shape[1]和size(1)是返回list索引所在的值

In [33]:
print(d.shape[1])
print(d.size(1))

3
3


## 张量dimension3 （常用于rnn）[seq_len,batch_size,embedding_dim]

In [34]:
a = torch.rand(1,2,3)#均匀分布

In [35]:
a

tensor([[[0.8090, 0.8327, 0.4948],
         [0.9830, 0.7262, 0.0874]]])

In [36]:
a.shape

torch.Size([1, 2, 3])

In [37]:
list(a.shape)

[1, 2, 3]

## 张量dimension4（常用于表示图片类型）[batch_size,channel,height,width]

In [38]:
a = torch.rand(2,3,28,28)#两张图片，每张图片为3通道，大小为28*28

In [39]:
a

tensor([[[[4.8047e-01, 5.9468e-01, 7.6418e-01,  ..., 1.0135e-01,
           6.9445e-01, 2.6139e-01],
          [4.4090e-01, 3.5528e-01, 5.5874e-01,  ..., 3.6104e-01,
           3.9500e-01, 3.4924e-01],
          [8.8561e-02, 9.2629e-01, 9.1399e-01,  ..., 4.5437e-01,
           1.4031e-01, 5.8683e-01],
          ...,
          [5.2951e-01, 9.6909e-01, 3.0365e-01,  ..., 1.5707e-01,
           3.7086e-01, 6.1920e-01],
          [1.0463e-01, 2.6287e-01, 3.5778e-02,  ..., 4.3312e-02,
           8.4704e-01, 3.4403e-01],
          [3.3356e-01, 8.6264e-01, 4.6127e-02,  ..., 9.7742e-01,
           5.0236e-01, 8.7359e-01]],

         [[3.4372e-01, 8.2687e-01, 2.1133e-01,  ..., 6.7722e-01,
           4.5240e-01, 3.9077e-02],
          [9.5789e-01, 2.0518e-01, 4.9212e-01,  ..., 4.5416e-01,
           6.0095e-01, 1.7525e-01],
          [9.1348e-01, 4.1107e-01, 5.8294e-01,  ..., 7.6592e-01,
           1.8563e-01, 5.0034e-01],
          ...,
          [8.0598e-01, 3.4932e-01, 6.2039e-01,  ..., 3.5718

In [40]:
a.shape

torch.Size([2, 3, 28, 28])

In [41]:
a.size()

torch.Size([2, 3, 28, 28])

In [42]:
a.dim()

4

In [43]:
a.numel() #2*3*28*28，全部元素个数,num of element

4704

# 2.创建Tensor

In [45]:
## 方法一：import from numpy 
a = np.array([1.,2.3])
torch.from_numpy(a)

tensor([1.0000, 2.3000], dtype=torch.float64)

In [47]:
a = np.ones([2,2])
torch.from_numpy(a)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

In [48]:
# 方法二：import from list
torch.tensor([2.,3.4])#小写的tensor接收的是实际的数据，大写的Tensor接收的是数据的维度

tensor([2.0000, 3.4000])

In [49]:
torch.FloatTensor(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [51]:
# 方法三：未初始化的方法（作为容器，要用其他类型把数据覆盖掉，数据可能非常大或者非常小）
torch.empty(1,2)

tensor([[0., 0.]])

In [53]:
torch.FloatTensor(1,3,4,4)

tensor([[[[ 0.0000e+00,  0.0000e+00,  6.5559e-10,  6.6762e-07],
          [ 4.1260e-08,  5.3484e+22,  4.2423e-08,  3.4005e-06],
          [ 2.6854e-06,  6.7445e-10,  3.3425e+21,  2.0975e-07],
          [ 6.6453e-07,  2.6100e+20,  2.6081e-09,  1.6994e-04]],

         [[ 1.3458e+22,  1.6996e-04,  6.2918e-43,  0.0000e+00],
          [-8.0827e+25,  4.5797e-41,  4.7487e+00,  3.0740e-41],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  3.0739e-41,  7.2646e+22,  7.2250e+28]],

         [[ 2.5226e-18,  2.4283e-18,  2.6302e+20,  6.1949e-04],
          [ 1.0256e-08,  4.2004e-05,  3.0613e+12,  6.9372e-07],
          [ 1.0683e-05,  1.6803e-04,  1.2611e+16,  1.2849e+31],
          [ 1.8395e+25,  6.1963e-04,  8.3753e-10,  4.3246e-05]]]])

## 随机初始化（rand[0,1]均匀分布,rand_like(tensor)把tensor.size()赋进去再随机生成,randint[min,max）)

In [55]:
a = torch.rand(2,2)

In [57]:
b = torch.rand_like(a)
b

tensor([[0.3186, 0.5089],
        [0.8489, 0.5746]])

In [58]:
c = torch.randint(0,10,[2,2])#第一个参数是最小值，第二个参数是最大值，第三个参数是shape也就是list类型

In [59]:
c

tensor([[7, 6],
        [4, 4]])

## 正态分布(randn[mean = 0,std = 1],自定义均值和方差torch.normal(mean= ,std = ))

In [62]:
torch.normal(mean = torch.full([10],0),std = torch.arange(1,0,-0.1))#然后可以再自己重新reshape

tensor([-0.6785, -0.4928,  0.5218, -1.4015,  0.1572,  0.1674,  0.0416, -0.2004,
        -0.5279, -0.0224])

## 其他
* torch.full
* torch.arange
* torch.linspace
* torch.logspace
** linspace和logspace都是等分的api，左闭右闭，log返回的是10的n次方 **
* torch.randperm

In [63]:
torch.full([],7)

tensor(7.)

In [64]:
torch.full([1],7)

tensor([7.])

In [65]:
torch.full([2,2],7)

tensor([[7., 7.],
        [7., 7.]])

In [66]:
torch.full([2,3,4],7)

tensor([[[7., 7., 7., 7.],
         [7., 7., 7., 7.],
         [7., 7., 7., 7.]],

        [[7., 7., 7., 7.],
         [7., 7., 7., 7.],
         [7., 7., 7., 7.]]])

In [68]:
torch.arange(0,10,2)#生成 [0，n-1）的等差数列，steps = 2,左闭右开

tensor([0, 2, 4, 6, 8])

In [70]:
torch.linspace(0,10,steps = 13)#这里的steps是等分的数量

tensor([ 0.0000,  0.8333,  1.6667,  2.5000,  3.3333,  4.1667,  5.0000,  5.8333,
         6.6667,  7.5000,  8.3333,  9.1667, 10.0000])

In [71]:
torch.logspace(0,10,steps = 13)

tensor([1.0000e+00, 6.8129e+00, 4.6416e+01, 3.1623e+02, 2.1544e+03, 1.4678e+04,
        1.0000e+05, 6.8129e+05, 4.6416e+06, 3.1623e+07, 2.1544e+08, 1.4678e+09,
        1.0000e+10])

## 全0全1对角为1即为torch.ones  torch.zeros  torch.eye

In [73]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [74]:
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [75]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

## torch.randperm生成一个随机打散的索引

In [76]:
torch.randperm(10)

tensor([8, 4, 2, 3, 7, 1, 0, 5, 9, 6])

In [77]:
a = torch.rand(3,3)
b = torch.rand(3,3)

In [78]:
print(a)
print(b)

tensor([[0.9363, 0.6562, 0.4548],
        [0.2122, 0.1628, 0.3821],
        [0.9045, 0.1629, 0.3243]])
tensor([[0.0313, 0.3548, 0.4061],
        [0.6452, 0.2382, 0.4570],
        [0.9579, 0.0612, 0.0718]])


In [82]:
idx = torch.randperm(3)

In [83]:
a[idx]

tensor([[0.9045, 0.1629, 0.3243],
        [0.2122, 0.1628, 0.3821],
        [0.9363, 0.6562, 0.4548]])

In [84]:
b[idx]

tensor([[0.9579, 0.0612, 0.0718],
        [0.6452, 0.2382, 0.4570],
        [0.0313, 0.3548, 0.4061]])

# 3.索引和切片

## Indexing

In [87]:
a = torch.rand(4,3,28,28)#4张图片3通道高宽28*28

In [88]:
a[0].shape#取第一章图片

torch.Size([3, 28, 28])

In [90]:
a[0,0].shape#取第一章图片的第0个通道上的像素点

torch.Size([28, 28])

In [91]:
a[0,0,2,4]#取第0张图片第0个通道第三行第五列的像素点

tensor(0.6755)

## SELECT first/last N

In [93]:
a.shape

torch.Size([4, 3, 28, 28])

In [94]:
a[:2].shape#取0-1[2,3,28,28]

torch.Size([2, 3, 28, 28])

In [96]:
a[:2,:1,:,:].shape#取第一张和第二章图片的第0个通道【2,1,28,28】    ——》2（2不取）  -》1（1不取）

torch.Size([2, 1, 28, 28])

In [98]:
a[:2,-1:,:,:].shape  #正着索引是[0,1,2],倒着索引是[-3,-2,-1]取第一站和第二章图片的最后一个通道[2,1,28,28]

torch.Size([2, 1, 28, 28])

In [100]:
a[:2,-2:,:,:].shape

torch.Size([2, 2, 28, 28])

## select steps隔行采样

In [102]:
a[:,:,0:28:2,0:28:2].shape

torch.Size([4, 3, 14, 14])

In [104]:
a[:,:,::2,::2].shape

torch.Size([4, 3, 14, 14])

## 使用特定的索引index_select

In [105]:
print(a.index_select(2,torch.arange(8)).shape)# 第一个参数是dimension，第二个维度是索引但是必须是tensor类型

torch.Size([4, 3, 8, 28])


## 使用掩码索引masked_select  把数据打平以后取出大于0.5的值
## take函数：在原来的Tensor的shape基础上打平，然后在打平后的Tensor上进行索引

In [109]:
x = torch.randn(3,4)
x

tensor([[-1.0461,  1.4568, -0.1260, -1.5518],
        [ 0.7922, -0.1101,  0.4217, -1.8575],
        [ 0.3839, -0.5328, -0.2686, -0.9149]])

In [112]:
mask = x.ge(0.5)  #greater equal:》=
mask

tensor([[False,  True, False, False],
        [ True, False, False, False],
        [False, False, False, False]])

In [113]:
torch.masked_select(x,mask)

tensor([1.4568, 0.7922])

In [115]:
src = torch.tensor([[2,3,4],[3,4,4]])
torch.take(src,torch.tensor([0,1,2,4]))

tensor([2, 3, 4, 4])

# 4.维度变换
* reshape/view
* Squeeze/unsqueeze
* transpose/T/permute
* expand/repeat

In [116]:
a = torch.rand(4,1,28,28)

In [117]:
a.shape

torch.Size([4, 1, 28, 28])

In [120]:
b = a.view(4,28*28)

In [121]:
b.shape

torch.Size([4, 784])

In [122]:
a.reshape(4,28*28).shape

torch.Size([4, 784])

## unsqueeze:增加一个维度但是没有增加数据[-a.dim()-1,a.dim+1)

In [123]:
a.shape

torch.Size([4, 1, 28, 28])

In [124]:
a.unsqueeze(0).shape

torch.Size([1, 4, 1, 28, 28])

In [127]:
a.unsqueeze(4).shape

torch.Size([4, 1, 28, 28, 1])

In [128]:
a.unsqueeze(-1).shape

torch.Size([4, 1, 28, 28, 1])

In [129]:
a.unsqueeze(-3).shape

torch.Size([4, 1, 1, 28, 28])

In [130]:
# eg:bias维度广播后相加
a = torch.rand(32) 
b = torch.rand(4,32,14,14)

In [131]:
print(a.shape)
print(b.shape)

torch.Size([32])
torch.Size([4, 32, 14, 14])


In [133]:
a.unsqueeze(0).unsqueeze(2).unsqueeze(3).shape

torch.Size([1, 32, 1, 1])

## squeeze不给参数就会size = 1的都挤压掉，给idx就是哪个维度就挤压哪个维度，如果size 不为1就不变

In [139]:
b = a.unsqueeze(0).unsqueeze(2).unsqueeze(3)

In [140]:
b.shape

torch.Size([1, 32, 1, 1])

In [142]:
b.squeeze().shape

torch.Size([32])

In [143]:
b.squeeze(-1).shape

torch.Size([1, 32, 1])

## Expand/Repeat
* Expand:broadcasting
* Repeat:memory copied

# Expand  首先维度一定是相同的，在某个维度上可以从1到n的扩张但是不为1就不可以扩张,如果是-1的话就代表此维度不变

In [145]:
a = torch.rand(4,32,14,14)

In [146]:
b = torch.rand(32)

In [147]:
b.shape

torch.Size([32])

In [149]:
b = b.unsqueeze(0).unsqueeze(2).unsqueeze(3)

In [150]:
b.shape

torch.Size([1, 32, 1, 1])

In [152]:
b.expand(4,32,14,14).shape

torch.Size([4, 32, 14, 14])

In [154]:
b.expand(-1,-1,14,14).shape

torch.Size([1, 32, 14, 14])

## repeat就是每个维度上重复的次数

In [155]:
b.shape

torch.Size([1, 32, 1, 1])

In [156]:
b.repeat(4,32,1,1).shape

torch.Size([4, 1024, 1, 1])

In [157]:
b.shape

torch.Size([1, 32, 1, 1])

## .t()只能在2D的数据上使用

In [159]:
a = torch.rand(3,2)

In [160]:
a

tensor([[0.0731, 0.9879],
        [0.1511, 0.5072],
        [0.9930, 0.6120]])

In [161]:
a.t()

tensor([[0.0731, 0.1511, 0.9930],
        [0.9879, 0.5072, 0.6120]])

## transpose()维度交换，contiguous()是把数据变成连续，只能两个维度

In [163]:
a = torch.randn(4,3,28,28)

In [164]:
# a:[b,c,h,w]
a.transpose(1,3).shape #[b,w,h,c]

torch.Size([4, 28, 28, 3])

In [166]:
a.transpose(1,3).view(4,28*28*3).view(4,3,28,28).shape

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [167]:
a.transpose(1,3).contiguous().view(4,28*28*3).view(4,3,28,28).shape

torch.Size([4, 3, 28, 28])

In [181]:
a = torch.rand(4,3,2,2)

In [182]:
a

tensor([[[[0.3557, 0.6806],
          [0.0900, 0.0207]],

         [[0.1401, 0.4575],
          [0.2210, 0.8014]],

         [[0.6919, 0.3722],
          [0.0165, 0.7144]]],


        [[[0.2015, 0.0646],
          [0.2546, 0.0556]],

         [[0.7257, 0.3902],
          [0.9679, 0.7769]],

         [[0.5042, 0.2042],
          [0.4731, 0.8164]]],


        [[[0.7392, 0.6723],
          [0.1356, 0.0991]],

         [[0.8852, 0.5821],
          [0.0574, 0.4517]],

         [[0.3623, 0.8477],
          [0.8045, 0.0305]]],


        [[[0.4684, 0.8605],
          [0.4217, 0.7938]],

         [[0.6087, 0.0547],
          [0.8376, 0.2875]],

         [[0.3410, 0.3454],
          [0.2821, 0.4179]]]])

In [185]:
# [b,c,h,w]=[4,3,2,2]=>transpose[4,2,2,3]
b = a.transpose(1,3).contiguous().view(4,2,2,3).transpose(1,3)

In [186]:
torch.all(torch.eq(a,b))

tensor(True)

## permute可以多个维度进行交换

In [187]:
a.shape

torch.Size([4, 3, 2, 2])

In [188]:
# [b,c,h,w]=>[b,h,w,c]
a.permute(0,2,3,1)

tensor([[[[0.3557, 0.1401, 0.6919],
          [0.6806, 0.4575, 0.3722]],

         [[0.0900, 0.2210, 0.0165],
          [0.0207, 0.8014, 0.7144]]],


        [[[0.2015, 0.7257, 0.5042],
          [0.0646, 0.3902, 0.2042]],

         [[0.2546, 0.9679, 0.4731],
          [0.0556, 0.7769, 0.8164]]],


        [[[0.7392, 0.8852, 0.3623],
          [0.6723, 0.5821, 0.8477]],

         [[0.1356, 0.0574, 0.8045],
          [0.0991, 0.4517, 0.0305]]],


        [[[0.4684, 0.6087, 0.3410],
          [0.8605, 0.0547, 0.3454]],

         [[0.4217, 0.8376, 0.2821],
          [0.7938, 0.2875, 0.4179]]]])