# 1.拼接与拆分
* cat拼接操作torch.cat([tensor1,tensor2],dim = dim)
* stack拼接操作
* split分割操作
* chunk分割操作

In [1]:
# cat和concat同
import numpy as np
import torch 
a = torch.randn(2,3,1)
b = torch.randn(2,3,4)

In [2]:
torch.cat([a,b],dim = 2).shape

torch.Size([2, 3, 5])

## stack拼接操作
* 与cat不同的是，stack是在拼接的同时，在指定dim处插入维度后拼接(<font color="#660000">create new dim</font> )
* stack需要保证两个Tensor的shape是一致的，这就像有两类东西，他们的属性都是一样的
* 使用stack时要指定一个维度位置，在那个位置之前会插入一个新的维度
* 因为两类东西合并过来所以这个新的维度size是2，通过指定这个维度是0或1来选择性别是男还是女

In [4]:
a1 = torch.rand(4,3,2)
a2 = torch.rand(4,3,2)
torch.stack([a1,a2],dim = 2).shape

torch.Size([4, 3, 2, 2])

In [5]:
torch.cat([a1,a2],dim = 2).shape

torch.Size([4, 3, 4])

### A班级32个人每个人8门分数，B班级同样，合成一张表应该是[2,32,8]取0就是第一个班级反之则是第二个维度

## split分割操作（给的是拆分后的长度），返回的是一个元祖：BY Len
* 指定拆分dim
* 按长度拆分，给定拆分后的数据大小

In [6]:
a1 = torch.randn(2,3,4)
a2 = torch.randn(1,3,4)
c = torch.cat([a1,a2],dim = 0)

In [7]:
c.shape

torch.Size([3, 3, 4])

In [9]:
# 指定拆分dim，均分，要给出拆分后的len
r1,r2,r3 = c.split(1,dim = 0)

In [10]:
print(r1.shape,r2.shape,r3.shape)

torch.Size([1, 3, 4]) torch.Size([1, 3, 4]) torch.Size([1, 3, 4])


In [13]:
aa,bb = c.split([2,1],dim = 0)

In [14]:
print(aa.shape,bb.shape)

torch.Size([2, 3, 4]) torch.Size([1, 3, 4])


### chunk分割操作(By num)
* chunk是在指定dim下按个数拆分，给定平均拆分的个数

In [17]:
c.shape

torch.Size([3, 3, 4])

In [19]:
c.chunk(2,dim = 0)

(tensor([[[ 1.3427e-01, -7.1640e-01,  4.0773e-01, -4.4941e-01],
          [-4.8573e-01,  4.5632e-01, -9.9357e-01, -5.0688e-01],
          [ 2.0265e-01,  3.8068e-01,  1.9989e-01, -1.3059e+00]],
 
         [[ 1.0998e+00,  3.5540e-01, -2.1332e+00, -1.6103e+00],
          [-1.0672e-03,  2.4409e-01,  6.7941e-01,  5.6289e-01],
          [ 1.1670e+00, -1.1564e+00, -4.6411e-01,  3.1277e-01]]]),
 tensor([[[-1.4779,  1.1341, -1.2432, -0.2920],
          [-0.3101,  1.1257,  0.2624, -0.7134],
          [ 0.4732, -0.0759, -1.3212, -1.1806]]]))

# 2.tensor的基本运算（basic直接用重载的+ - * /就可以）
* 加法(a+b,torch.add(a,b))
* 减法(a-b,torch.sub(a,b))
* 乘法(*,torch.mul(a,b))
* 除法(/,torch.div(a,b)),//整除

In [22]:
a = torch.rand(3,4)
b = torch.rand(4)

In [23]:
a+b

tensor([[1.0266, 0.9550, 1.0609, 0.8649],
        [1.2378, 1.1906, 0.4274, 0.2775],
        [1.2009, 1.3065, 0.2823, 0.2063]])

In [24]:
torch.add(a,b)

tensor([[1.0266, 0.9550, 1.0609, 0.8649],
        [1.2378, 1.1906, 0.4274, 0.2775],
        [1.2009, 1.3065, 0.2823, 0.2063]])

In [25]:
a-b

tensor([[ 0.1251, -0.8959,  0.6404,  0.6704],
        [ 0.3363, -0.6603,  0.0070,  0.0830],
        [ 0.2994, -0.5444, -0.1381,  0.0118]])

In [26]:
torch.sub(a,b)

tensor([[ 0.1251, -0.8959,  0.6404,  0.6704],
        [ 0.3363, -0.6603,  0.0070,  0.0830],
        [ 0.2994, -0.5444, -0.1381,  0.0118]])

In [27]:
a*b

tensor([[0.2595, 0.0274, 0.1788, 0.0746],
        [0.3548, 0.2454, 0.0457, 0.0175],
        [0.3381, 0.3526, 0.0152, 0.0106]])

In [28]:
torch.mul(a,b)

tensor([[0.2595, 0.0274, 0.1788, 0.0746],
        [0.3548, 0.2454, 0.0457, 0.0175],
        [0.3381, 0.3526, 0.0152, 0.0106]])

In [29]:
a/b

tensor([[1.2775, 0.0320, 4.0462, 7.8945],
        [1.7461, 0.2865, 1.0331, 1.8539],
        [1.6642, 0.4117, 0.3429, 1.1212]])

In [30]:
torch.div(a,b)

tensor([[1.2775, 0.0320, 4.0462, 7.8945],
        [1.7461, 0.2865, 1.0331, 1.8539],
        [1.6642, 0.4117, 0.3429, 1.1212]])

In [33]:
torch.all(torch.eq(a-b,torch.sub(a,b)))

tensor(True)

## 矩阵乘法(* 是element wise,matmul是矩阵相乘marix)
* torch.mm(only for 2d，不推荐)
* torch.matmul()和@（推荐）

In [34]:
a = torch.rand(3,4)
b = torch.rand(4,3)

In [35]:
c = torch.matmul(a,b)

In [37]:
c.shape

torch.Size([3, 3])

In [40]:
(a@b).shape

torch.Size([3, 3])

In [41]:
# torch里面默认hidden size是在前面的
x = torch.randn(4,784)
w = torch.randn(512,784)
h1 = torch.matmul(x,w.t())
h1.shape

torch.Size([4, 512])

## 多维矩阵相乘，定义其矩阵乘法只在最后的两个维度上，要求前面的维度必须保持一致，就像矩阵的索引一样，并且运算操作符只有matmul()
## ‘矩阵索引维度’如果符合Broadcasting机制，也会自动做广播，然后相乘

In [43]:
a = torch.rand(4,3,28,64)
b = torch.rand(4,3,64,32)

In [44]:
torch.matmul(a,b).shape

torch.Size([4, 3, 28, 32])

In [45]:
c = torch.rand(4,1,32,16)

In [46]:
torch.matmul(b,c).shape

torch.Size([4, 3, 64, 16])

## 次方pow(**操作)
## 开方sqrt
## 指数exp与对数log运算
## 近似值运算
## 裁剪运算clamp

In [57]:
a = torch.full([2,2],1)
c = a**2

In [50]:
c

tensor([[9., 9.],
        [9., 9.]])

In [51]:
a.pow(2)

tensor([[9., 9.],
        [9., 9.]])

In [52]:
a.pow(0.5)

tensor([[1.7321, 1.7321],
        [1.7321, 1.7321]])

In [53]:
torch.exp(a)

tensor([[20.0855, 20.0855],
        [20.0855, 20.0855]])

In [54]:
torch.log(a)

tensor([[1.0986, 1.0986],
        [1.0986, 1.0986]])

## 近似值运算
## floor(),ceil(),trunc(),frac()取下，取上，取整数部分，取小数部分

In [59]:
a = torch.tensor(3.14)
print(a.floor(),a.ceil(),a.trunc(),a.frac())

tensor(3.) tensor(4.) tensor(3.) tensor(0.1400)


In [60]:
a.round()#四舍五入

tensor(3.)

In [62]:
a = torch.tensor(3.55)
a.round()

tensor(4.)

## 裁剪运算clamp
* 常用于梯度裁剪（gradient clipping）
* (min,max):小于min的都设置为min,大于max的都设置为max
* 实际使用时，可以查看梯度的（L2范数）模来看看需不需要做处理:w.grad.norm(2)<br/>
    w是weight权重，w.grad才是梯度

In [64]:
grad  = torch.rand(2,3)*15

In [65]:
grad.max()

tensor(14.8773)

In [66]:
grad.median()

tensor(5.1822)

In [67]:
grad.clamp(10)#小于10 的都设置为10

tensor([[10.0000, 10.0000, 10.0000],
        [14.6058, 14.8773, 10.0000]])

In [69]:
grad

tensor([[ 5.0317,  5.1822,  2.5087],
        [14.6058, 14.8773,  6.4951]])

In [70]:
grad.clamp(0,10)#大于10的都设置为10

tensor([[ 5.0317,  5.1822,  2.5087],
        [10.0000, 10.0000,  6.4951]])

## 实际网络中则：
for w in []：<br/>
&ensp;&ensp;&ensp;&ensp;&ensp;    w.grad.norm(2).clamp(min,max)

# 3.统计属性
* norm求范数
* mean sum
* prod
* max,min,argmin,argmax
* kthvalue,topk

In [1]:
import torch
a = torch.full([8],1)

In [2]:
b = a.view(2,4)
c = a.view(2,2,2)

In [3]:
b

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [4]:
c

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [8]:
# 求L1范数（所有元素绝对值求和）
print(a.norm(1),b.norm(1),c.norm(1))

tensor(8.) tensor(8.) tensor(8.)


In [9]:
# 求L2范数（所有元素平方和再开根）
print(a.norm(2),b.norm(2),c.norm(2))

tensor(2.8284) tensor(2.8284) tensor(2.8284)


In [10]:
# 在b的1号维度上求L1范数，原来shape：【2,4】-》【2】
print(b.norm(1,dim = 1))

tensor([4., 4.])


In [11]:
# 在c的0号维度上求L1范数：原来shape:[2,2,2]->[2,2]
c.norm(1,dim = 0)

tensor([[2., 2.],
        [2., 2.]])

In [12]:
# 在c的0号维度上求L2范数：原来shape:[2,2,2]->[2,2]
c.norm(2,dim = 0)

tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])

In [14]:
c.norm(2,dim =2 )

tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])

## 均值、累加、最大、最小、累积
* mean(),sum(),max(),min(),prod()
* 最大最小值索引argmax(),argmin()  默认会将Tensor打平后返回索引，需要在指定维度上求最大值或最小值索引

In [15]:
b = torch.arange(8).reshape(2,4).float()

In [16]:
b

tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]])

In [17]:
print(b.mean(),b.sum(),b.max(),b.min(),b.prod())

tensor(3.5000) tensor(28.) tensor(7.) tensor(0.) tensor(0.)


In [18]:
# 不指定维度，输出打平后的最大最小值索引
print(b.argmax(dim = 1))

tensor([3, 3])


In [19]:
print(b.argmin(dim = 1))

tensor([0, 0])


# dim/keepdim
* shape = [4,10],dim = 1时，保留原有的dimension

In [21]:
a = torch.rand(4,10)#若表示输出的4张图片的概率

In [22]:
a

tensor([[0.2827, 0.9541, 0.9447, 0.8730, 0.8279, 0.9905, 0.7006, 0.7855, 0.6530,
         0.9713],
        [0.4904, 0.2653, 0.2842, 0.5824, 0.7055, 0.0054, 0.4112, 0.6447, 0.0600,
         0.9502],
        [0.2862, 0.4512, 0.9707, 0.4806, 0.0211, 0.7702, 0.7046, 0.1101, 0.1658,
         0.9084],
        [0.7692, 0.4682, 0.1560, 0.7596, 0.4425, 0.9274, 0.8661, 0.6353, 0.1366,
         0.3940]])

In [24]:
value,indices = a.max(dim = 1)

In [25]:
value

tensor([0.9905, 0.9502, 0.9707, 0.9274])

In [26]:
indices

tensor([5, 9, 2, 5])

In [27]:
a.max(dim = 1,keepdim = True)#还是原来的2维度

torch.return_types.max(
values=tensor([[0.9905],
        [0.9502],
        [0.9707],
        [0.9274]]),
indices=tensor([[5],
        [9],
        [2],
        [5]]))

In [28]:
a.argmax(dim = 1,keepdim = True)

tensor([[5],
        [9],
        [2],
        [5]])

## topk和kthvalue
* 前k大topk(largest = True)/前k小（largest = False）的概率值及其索引
* 第k小（kthvalue）的概率值及其索引

In [29]:
# 4张图片每张图片有10个概率值
a = torch.rand(4,10)

In [30]:
a

tensor([[0.7479, 0.5610, 0.3722, 0.6786, 0.7533, 0.0202, 0.8349, 0.8613, 0.9257,
         0.3804],
        [0.4994, 0.7188, 0.5171, 0.7640, 0.1275, 0.3646, 0.6629, 0.4905, 0.3340,
         0.8945],
        [0.2287, 0.6874, 0.0505, 0.8138, 0.4300, 0.6897, 0.8790, 0.6564, 0.4669,
         0.3304],
        [0.7086, 0.6170, 0.5626, 0.3899, 0.5052, 0.6085, 0.2100, 0.0501, 0.8810,
         0.9383]])

In [31]:
a.topk(3,dim = 1)

torch.return_types.topk(
values=tensor([[0.9257, 0.8613, 0.8349],
        [0.8945, 0.7640, 0.7188],
        [0.8790, 0.8138, 0.6897],
        [0.9383, 0.8810, 0.7086]]),
indices=tensor([[8, 7, 6],
        [9, 3, 1],
        [6, 3, 5],
        [9, 8, 0]]))

In [32]:
a.topk(1,dim = 1)

torch.return_types.topk(
values=tensor([[0.9257],
        [0.8945],
        [0.8790],
        [0.9383]]),
indices=tensor([[8],
        [9],
        [6],
        [9]]))

In [33]:
a.topk(3,dim = 1,largest = False)#返回的是前3小的概率值及其索引

torch.return_types.topk(
values=tensor([[0.0202, 0.3722, 0.3804],
        [0.1275, 0.3340, 0.3646],
        [0.0505, 0.2287, 0.3304],
        [0.0501, 0.2100, 0.3899]]),
indices=tensor([[5, 2, 9],
        [4, 8, 5],
        [2, 0, 9],
        [7, 6, 3]]))

In [34]:
a.kthvalue(3,dim = 1,keepdim = True)#返回第3小的概率值及其索引

torch.return_types.kthvalue(
values=tensor([[0.3804],
        [0.3646],
        [0.3304],
        [0.3899]]),
indices=tensor([[9],
        [5],
        [9],
        [3]]))

In [35]:
# 如果不设置keepdim = True的话，那么只会返回一个维度
a.kthvalue(3,dim = 1)

torch.return_types.kthvalue(
values=tensor([0.3804, 0.3646, 0.3304, 0.3899]),
indices=tensor([9, 5, 9, 3]))

## 4.逻辑运算 >,>=,<,<=,!=,==

In [36]:
a>0

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])

In [37]:
a<0

tensor([[False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False]])

In [38]:
a>0.5

tensor([[ True,  True, False,  True,  True, False,  True,  True,  True, False],
        [False,  True,  True,  True, False, False,  True, False, False,  True],
        [False,  True, False,  True, False,  True,  True,  True, False, False],
        [ True,  True,  True, False,  True,  True, False, False,  True,  True]])

In [39]:
a<=0.5

tensor([[False, False,  True, False, False,  True, False, False, False,  True],
        [ True, False, False, False,  True,  True, False,  True,  True, False],
        [ True, False,  True, False,  True, False, False, False,  True,  True],
        [False, False, False,  True, False, False,  True,  True, False, False]])

In [40]:
a!=0.5

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])

In [41]:
a == 0.5  #类比torch.eq(a,a)element进行比较，但是equal就是单纯tensor进行比较

tensor([[False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False]])

In [42]:
torch.eq(a,a)

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])

In [43]:
torch.equal(a,a)

True

# 5.高阶操作
## 5.1 where
* 使用C = torch.where(condition,A,B)
* 其中A,B,C,condition是shape相同的Tensor
* C中的某些元素来自A，某些元素来自B，这由condition中对应位置的元素是1还是0来决定
* 如果condition对应位置元素是1，则C中的该位置的元素来自A中的该位置的元素
* 如果condition对应位置元素是0，则C中的该位置的元素来自B中的该位置的元素

In [44]:
cond = torch.rand(2,2)#代表概率

In [45]:
a = torch.ones(2,2,)

In [46]:
b = torch.zeros(2,2)

In [47]:
torch.where(cond>0.5,a,b)

tensor([[1., 1.],
        [0., 0.]])

## 5.2gather
* torch.gather(input,dim,index,out = None)对元素一个查表映射的操作

# 重新得到对应真实label
* argmax(pred) to get relative labeling
* on some condition,our label is distinct from relative labeling

# prob:[4,10]概率，得到对应的label:[0,9,6,10]
# 但是真实label有另外一张表[0,10]->[101,102,103,104,...]

In [49]:
prob = torch.rand(4,10)

In [50]:
prob

tensor([[0.4523, 0.3438, 0.3932, 0.7800, 0.1671, 0.7993, 0.1309, 0.4024, 0.9625,
         0.6708],
        [0.6166, 0.9762, 0.5407, 0.9257, 0.0993, 0.6589, 0.2343, 0.8837, 0.2495,
         0.0819],
        [0.3187, 0.8219, 0.9436, 0.0697, 0.0915, 0.9449, 0.7189, 0.9379, 0.4076,
         0.5902],
        [0.5678, 0.5421, 0.0695, 0.8479, 0.3161, 0.7877, 0.4201, 0.9348, 0.3059,
         0.2531]])

In [52]:
idx = prob.topk(3,dim = 1)

In [53]:
idx = idx[1] 

In [54]:
idx

tensor([[8, 5, 3],
        [1, 3, 7],
        [5, 2, 7],
        [7, 3, 5]])

In [55]:
label = torch.arange(10)+100

In [56]:
label

tensor([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [57]:
label = label.unsqueeze(0)

In [59]:
label  = label.expand(4,10)

In [60]:
torch.gather(label,dim = 1,index = idx.long())

tensor([[108, 105, 103],
        [101, 103, 107],
        [105, 102, 107],
        [107, 103, 105]])