In [3]:
import torch
a = torch.linspace(-100,100,10)

In [4]:
a

tensor([-100.0000,  -77.7778,  -55.5556,  -33.3333,  -11.1111,   11.1111,
          33.3333,   55.5555,   77.7778,  100.0000])

In [5]:
torch.sigmoid(a)

tensor([0.0000e+00, 1.6655e-34, 7.4564e-25, 3.3382e-15, 1.4945e-05, 9.9999e-01,
        1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00])

# 1.autograd.grad,自动求导
* 梯度计算torch.autograd.grad(loss,[w1,w2,...wn])
* 第一个参数是损失函数，第二个参数是该损失函数要求梯度的参数列表
* 对w求导，需要先指明w需要的梯度信息
w.requires_grad_()
* 返回结果grad_val是梯度列表，列表记录了每一个Tensor的梯度信息

In [6]:
x = torch.ones(1)

In [7]:
w = torch.full([1],2)

In [8]:
# y = wx+b(b取0)
import torch
from torch.nn import functional as F

In [9]:
mse = F.mse_loss(x*w,torch.ones(1))

In [10]:
# 对w求导，需要先指明w需要梯度信息
torch.autograd.grad(mse,[w])

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [12]:
w.requires_grad_()

tensor([2.], requires_grad=True)

In [14]:
torch.autograd.grad(mse,[w])#虽然指明了梯度信息但是要更新图指明w是需要梯度下降的

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [15]:
mse = F.mse_loss(x*w,torch.ones(1))

In [17]:
torch.autograd.grad(mse,[w])

(tensor([2.]),)

## loss.backword()
* 图的反向传播，自动求出该图上所有的需要计算梯度的参数相对于这个MSE的梯度
* 梯度信息会附加到每个梯度参数w的成员变量grad中，即w.grad就是这个参数的求导出来的梯度
* backward只能对一个标量求导，不能多个分量

In [32]:
x = torch.ones(1)

In [33]:
w = torch.full([1],2)
# w = torch.tensor(2.,requires_grad = True)

In [34]:
w.requires_grad_()

tensor([2.], requires_grad=True)

In [35]:
mse = F.mse_loss(x*w,torch.ones(1))

In [36]:
mse.backward()

In [37]:
w.grad

tensor([2.])

# 3.Softmax

In [12]:
import torch
a = torch.rand(3)

In [13]:
a.requires_grad_()

tensor([0.9213, 0.2952, 0.0706], requires_grad=True)

In [14]:
from torch.nn import functional as F
prob = F.softmax(a,dim = 0)

In [15]:
prob

tensor([0.5097, 0.2725, 0.2177], grad_fn=<SoftmaxBackward>)

In [8]:
prob.backward()# 注意只能对一个标量求导，prob是一个有3个值的一维向量会报错

RuntimeError: grad can be implicitly created only for scalar outputs

In [16]:
prob[0].backward(retain_graph = True)#只能求导一次，图就不存在了，所以需要设置retain_graph = True

In [ ]:
torch.autograd.grad(pr)