In [17]:
import torch
from torch import nn,optim
from torch.nn import functional as F
from torchvision import transforms

# 1.卷积层
* 1.1torch.nn.Conv2d()类式接口

* torch.nn.Conv2d(self,in_channels,out_channels,kernel_size,stride = 1,padding = 0,dilation = 1,groups = 1,bias = True)

In [3]:
x = torch.rand(1,1,28,28)
layer = nn.Conv2d(1,3,kernel_size=3,stride = 2,padding=1)
out = layer.forward(x)
print(out.shape)

torch.Size([1, 3, 14, 14])


## layer的相关属性：
* layer.weight.shape: [3,1,3,3]----------[out_channel,in_channel,kernel_size[0],kernel_size[1]]
* layer.bias.shape:[3]--------------[out_channel]


In [4]:
layer.weight.shape

torch.Size([3, 1, 3, 3])

In [5]:
layer.bias.shape

torch.Size([3])

In [6]:
layer.weight

Parameter containing:
tensor([[[[ 0.1138,  0.2175, -0.0684],
          [ 0.1857, -0.1687,  0.0562],
          [ 0.2764,  0.1258, -0.1745]]],


        [[[ 0.2960, -0.0936,  0.3059],
          [-0.0784,  0.1252,  0.2697],
          [ 0.1186,  0.1095, -0.0574]]],


        [[[-0.1110, -0.1180,  0.2755],
          [ 0.0597, -0.1091, -0.2511],
          [-0.0922,  0.0893, -0.2994]]]], requires_grad=True)

## F.conv2d()函数式接口
* pytorch里一般小写的都是函数式接口，相应的大写的是类接口

In [7]:
x = torch.rand(1,3,28,28)
w = torch.rand(16,3,3,3)
b = torch.rand([16])

In [8]:
print(w.shape,b.shape)

torch.Size([16, 3, 3, 3]) torch.Size([16])


In [9]:
out = F.conv2d(x,w,b,stride = 1,padding = 1)

In [11]:
out.shape

torch.Size([1, 16, 28, 28])

# 2.池化层Pooling(下采样)
* torch.nn.MaxPool2d(kernel_size,stride = None,padding = 0,dilation = 1,return_indices = False,ceil_mode = True)

* 参数
* kernel_size:max pooling 的窗口大小
* stride:maxpooling的窗口移动步长，默认是kernel_size
* padding:输入的每一条边补充0的层数
* dilation(int or tuple,optional):一个控制窗口中元素步幅的参数
* return_indices:如果等于True,会返回输出最大值的序号，对于上采样操作会有帮助
* ceil_mode：如果等于True,计算输出信号大小的时候，会使用向上取整，代替默认的向下取整的操作

In [12]:
x = out
layer = nn.MaxPool2d(2,stride=2)
out = layer(x)
print(out.shape)

torch.Size([1, 16, 14, 14])


## F.avg_pool2d()接口

In [14]:
x = out
out = F.avg_pool2d(x,2,stride = 2)
print(out.shape)

torch.Size([1, 16, 3, 3])


# 3.Relu激活函数
## 3.1 torch.nn.ReLU()类式接口
## 3.2F.relu()函数式接口

In [15]:
layer  = torch.nn.ReLU(inplace = True)
out = layer(x)
print(out.shape)

torch.Size([1, 16, 7, 7])


In [16]:
out = F.relu(x,inplace=True)
print(out.shape)

torch.Size([1, 16, 7, 7])


# 4.BatchNorm
* Feature scaling
    * Image normalization:
    normalize = transforms.Normalize(mean = [0.485,0.456,0.426],std = [0.229,0.224,0.225])# mean
* BatchNormalization

## nn.BatchNorm1d()

In [19]:
x = torch.rand(100,16,784)
layer = nn.BatchNorm1d(16)
out = layer(x)
out

tensor([[[ 1.4206,  1.6398,  1.2971,  ...,  1.4759, -0.9848,  0.2814],
         [ 1.4363,  0.5031,  0.2286,  ..., -0.3462,  1.1703, -0.0294],
         [-0.5562, -1.1518, -0.5014,  ..., -1.4636,  0.5836,  0.8287],
         ...,
         [-1.0556,  0.5869, -0.8668,  ...,  1.4058,  1.3721,  1.4407],
         [-1.2691, -0.9288, -0.0486,  ...,  1.1802, -0.2857,  0.1415],
         [ 1.2419, -0.8243,  1.3234,  ...,  0.8687,  0.9753, -0.7942]],

        [[ 0.1377,  1.5109,  0.8017,  ..., -0.6290, -0.3157, -0.1549],
         [ 1.0691, -0.5654, -0.9126,  ..., -0.1815,  1.1762, -0.1391],
         [ 0.1189,  0.2083,  0.1527,  ...,  1.0793, -0.7005,  1.7093],
         ...,
         [-0.1667, -1.3347,  1.4772,  ...,  1.2714,  0.3426, -1.4824],
         [ 1.2133,  0.3488, -0.1211,  ..., -1.0829,  0.4583, -0.8922],
         [ 0.7018,  0.3711, -1.3473,  ..., -0.3358, -0.6405, -0.4912]],

        [[ 0.8025, -1.6179, -1.2129,  ...,  0.7843, -0.7478,  1.5403],
         [-0.6379,  0.7117, -0.3140,  ...,  0

In [20]:
out.shape

torch.Size([100, 16, 784])

In [21]:
layer.running_mean.shape

torch.Size([16])

In [22]:
layer.running_var

tensor([0.9084, 0.9084, 0.9083, 0.9083, 0.9083, 0.9083, 0.9084, 0.9083, 0.9083,
        0.9083, 0.9083, 0.9083, 0.9083, 0.9083, 0.9083, 0.9083])

## layer.running_mean和running_var是全局的均值和方差

## nn.BatchNorm2d()

In [23]:
x = torch.rand(1,16,7,7)
layer = nn.BatchNorm2d(16)#传入通道数必须和上面的通道数目一致
out = layer(x)

In [24]:
out.shape

torch.Size([1, 16, 7, 7])

In [25]:
print(layer.running_mean.shape,layer.running_var.shape)

torch.Size([16]) torch.Size([16])


In [26]:
layer.weight

Parameter containing:
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       requires_grad=True)

In [27]:
layer.bias

Parameter containing:
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       requires_grad=True)

In [29]:
#查看一个网络层上的所有参数
vars(layer)

{'training': True, '_parameters': OrderedDict([('weight', Parameter containing:
               tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
                      requires_grad=True)), ('bias', Parameter containing:
               tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
                      requires_grad=True))]), '_buffers': OrderedDict([('running_mean',
               tensor([0.0511, 0.0486, 0.0552, 0.0550, 0.0502, 0.0507, 0.0482, 0.0467, 0.0524,
                       0.0558, 0.0546, 0.0539, 0.0485, 0.0487, 0.0518, 0.0457])),
              ('running_var',
               tensor([0.9097, 0.9089, 0.9069, 0.9068, 0.9082, 0.9089, 0.9094, 0.9078, 0.9081,
                       0.9078, 0.9078, 0.9094, 0.9078, 0.9080, 0.9109, 0.9093])),
              ('num_batches_tracked',
               tensor(1))]), '_backward_hooks': OrderedDict(), '_forward_hooks': OrderedDict(), '_forward_pre_hooks': OrderedDict(), '_state_dict_hooks': Order

In [ ]:
## 4.3Train和Test
* 类似于Dropout，BatchNormalization在训练和测试时的行为不同